//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_webforms {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl lblName;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl lblDesignation;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl NavBar;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl NavChild;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList1;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList2;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.TextBox TextBox2;
		
		protected System.Web.UI.WebControls.TextBox TextBox3;
		
		protected System.Web.UI.WebControls.TextBox TextBox4;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList3;
		
		protected System.Web.UI.WebControls.TextBox TextBox5;
		
		protected System.Web.UI.WebControls.TextBox TextBox6;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList4;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList5;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList6;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList7;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList8;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList9;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList10;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList11;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.WebControls.Button Button3;
		
		protected System.Web.UI.WebControls.Button Button4;
		
		protected System.Web.UI.WebControls.GridView grid1;
	}
}
